server:
  port: 8087
  ssl:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diplomdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

urls:
  embeddingRequestUrl: http://localhost:8000/hello?title=1234

