server:
  port: 8084
  ssl:
    enabled: false


bot:
  name: ${botName}
  token: ${botToken}
  uri: ${botUri}

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mainGroup

